imageTag: 0.0.2
appName: dailyfeed-member
replicas: 1
profile: local
envValues:
- name: SERVER_PORT
  value: "8080"
- name: MEMBER_SERVICE_URL
  value: http://dailyfeed-member-svc.dailyfeed.svc.cluster.local
- name: SEARCH_SERVICE_URL
  value: http://dailyfeed-search-svc.dailyfeed.svc.cluster.local
- name: CONTENT_SERVICE_URL
  value: http://dailyfeed-content-svc.dailyfeed.svc.cluster.local
configSecretItems:
- kafka
- redis-nosecret
- mysql
- mongodb
porbeValues:
  startup:
    failureThreshold: 60
