name: Docker Build and Push

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:
    inputs:
      image_version:
        description: 'Docker image version (e.g., beta-20251023-0001)'
        required: true
        type: string

env:
  # 기본 이미지 버전 (자동 생성: beta-YYYYMMDD-HHMM)
  DEFAULT_IMAGE_VERSION: beta-${{ github.run_number }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    # GitHub Environment를 사용하는 경우 (권장)
    # environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Determine Image Version
        id: version
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "IMAGE_VERSION=${{ inputs.image_version }}" >> $GITHUB_ENV
          else
            # 자동 빌드 시 날짜 기반 버전 생성
            IMAGE_VERSION="beta-$(date +'%Y%m%d-%H%M')"
            echo "IMAGE_VERSION=${IMAGE_VERSION}" >> $GITHUB_ENV
          fi
          echo "Selected image version: ${IMAGE_VERSION}"

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          chmod +x ./jibDockerBuild.sh
          ./jibDockerBuild.sh
        env:
          IMAGE_VERSION: ${{ env.IMAGE_VERSION }}

      - name: Build Summary
        run: |
          echo "### Docker Build Summary :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Image**: alpha300uk/dailyfeed-member-svc" >> $GITHUB_STEP_SUMMARY
          echo "- **Tag**: ${{ env.IMAGE_VERSION }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Triggered by**: ${{ github.actor }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Commit**: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY